### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by 406baoqichao406** [NUAAXXY/CNN-FaceKeyPoint-Detection#1]
When I train the model, which is entered. / Bootstrap.sh always show sh: 1: caffe not found, what is the problem? How to deal with it?

**Comment by XingyuXie** [comment]
Firstly, you should make sure that you install caffe correctly including the pycaffe. Then, this is a project of my course. Hence, I wrote the absolute path in the .py file. You should change it according to your own environment.

**Comment by 406baoqichao406** [comment]
I have compiled caffe, caffe environment variables have been on the computer, py file path has been changed over. Do py files have caffe related to the path?

**Comment by XingyuXie** [comment]
@406baoqichao406 
yes, In data_level1.py line 15,16

**Comment by 406baoqichao406** [comment]
Can I add your WeChat? Because these have been changed, still not.

**Comment by XingyuXie** [comment]
@406baoqichao406  15651670027
